name: build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Install
              run: npm install --force
            - name: Make
              run: npm run make --force
            - name: Check Artifacts
              run: ls -r ./out/make