name: release

on:
    push:
        tags:
            - 'v*'
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm install --force
      - name: Make
        run: npm run make --force
      - name: Get version
        id: get_version
        run: |
             npm run gen-version
             echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-panel-windows-${{steps.get_version.version}}
          path: ./out/make/squirrel.windows/x64/*.exe
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm install --force
      - name: Make
        run: npm run make --force
      - name: Get version
        id: get_version
        run: |
             npm run gen-version
             echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-panel-linux-${{steps.get_version.version}}
          path: ./out/make/deb/x64/*.deb
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm install --force
      - name: Make
        run: npm run make --force
      - name: Get version
        id: get_version
        run: |
             npm run gen-version
             echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-panel-macos-${{steps.get_version.version}}
          path: ./out/make/zip/darwin/arm64/*.zip
  release:
    runs-on: ubuntu-latest
    needs: 
      - windows
      - linux
      - macos
    permissions:
        contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Get Version
        id: get_version
        run: |
             npm run gen-version
             echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Download Artifact (Windows)
        uses: actions/download-artifact@v4
        with:
          name: github-panel-windows-${{steps.get_version.version}}
          path: out/make/squirrel.windows/x64/
      - name: Download Artifact (Linux)
        uses: actions/download-artifact@v4
        with:
          name: github-panel-windows-${{steps.get_version.version}}
          path: out/make/deb/x64/
      - name: Download Artifact (MacOS)
        uses: actions/download-artifact@v4
        with:
          name: github-panel-windows-${{steps.get_version.version}}
          path: out/make/zip/darwin/arm64/
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{steps.get_version.version}}
          artifacts: "out/make/zip/darwin/arm64/*.zip,out/make/deb/x64/*.deb,out/make/squirrel.windows/x64/*.exe"