name: release

on:
    push:
        tags:
            - 'v*'
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        permissions:
            contents: write
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Install
              run: npm install --force
            - name: Make
              run: npm run make --force
            - name: Get version
              id: get_version
              run: |
                npm run gen-version
                echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
            - name: Release
              uses: ncipollo/release-action@v1
              with:
                  name: Release ${{steps.get_version.version}}
                  artifacts: "./out/make/zip/darwin/arm64/github-panel-darwin-arm64-0.1.0.zip,./out/make/deb/x64/github-panel_0.1.0_amd64.deb,./out/make/rpm/x64/github-panel-0.1.0-1.x86_64.rpm,./out/make/squirrel.windows/x64/github-panel-0.1.0 Setup.exe"